helmDefaults:
  atomic: true
  cleanupOnFail: true

repositories:
  - name: external-secrets
    url: "https://charts.external-secrets.io/"

commonLabels:
  managedBy: Helmfile

releases:
  - name: external-secrets
    namespace: "test"
    chart: external-secrets/external-secrets
    version: "0.5.3"

kubeVersion: v1.22
